### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ahibahi** [zafarali/MindReader#1]
Hi,

I am getting an error when am trying to run this code
I downloaded and added the data as requested
The error is attached within this post.

Thank you
![error](https://cloud.githubusercontent.com/assets/6408125/11450107/2f937d54-95b7-11e5-9fb9-2768c8221b70.JPG)

**Comment by zafarali** [comment]
Hi @ahibahi,

Just to get this out of the way, the code is not ready for production yet. However, the main error with your code is the following:

``` python
LRs[label_name].fit[ X, Y[:,i] ]
```

`LRs[label]` is a classifier object and thus you cannot index it. Infact `fit()` is a function and you should change the line to:

``` python
LRs[label_name].fit( X, Y[:,i] )
```

Let me know if that fixes your problem!

**Comment by ahibahi** [comment]
It's still the same code?
What's the change that has to be made?
Sorry for the trouble. I am new to this field and I need some practice to learn.

**Comment by zafarali** [comment]
I changed the square brackets to parenthesis.

We use square brackets to index arrays and lists in python while
parenthesis are used to call functions.

**Comment by ahibahi** [comment]
It works :D
Thank you very much

**Comment by zafarali** [comment]
Great! Good luck!
